
name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Containerize & Deploy to Fly
        run: flyctl deploy --detach
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
